import type { Metadata } from "next";
import { Sour_Gummy } from "next/font/google";
import "../../globals.css";

import ParentHeader from "./../Components/ParentHeader";
import ParentNavbar from "./../Components/ParentNavbar";

const sourGummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
  weight: "400", // only weight available
});

export const metadata: Metadata = {
  title: "hackathon app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourGummy.className} antialiased`}>
        <ParentHeader />
        {children}
        <ParentNavbar />
      </body>
    </html>
  );
}