import type { Metadata } from "next";
import { Sour_Gummy } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const sourGummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
  weight: "400", // only weight available
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sourGummy.variable}>
      <body>{children}</body>
    </html>
  )
}
